sudo: require
language: python

python:
  - 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev
      
script:
  - cmake -H. -Bbuild 
  - cmake --build build
  - ./bin/test_davidson
  
branches:
  only:
   - master

