dist: xenial
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev
      - libeigen3-dev
      - libboost-all-dev


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes -c conda-forge cxxopts

script:
  - cmake -H. -Bbuild 
  - cmake --build build
  - ./bin/test_davidson
  
branches:
  only:
   - master

